import { Meta } from '@storybook/react'
import { CharacterButton } from './index'

export default { title: 'components/molecules/CharacterButton' } satisfies Meta<typeof CharacterButton>

export const character01 = () => <CharacterButton imageSource='/images/characters/01.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character02 = () => <CharacterButton imageSource='/images/characters/02.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character03 = () => <CharacterButton imageSource='/images/characters/03.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character04 = () => <CharacterButton imageSource='/images/characters/04.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character05 = () => <CharacterButton imageSource='/images/characters/05.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character06 = () => <CharacterButton imageSource='/images/characters/06.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character07 = () => <CharacterButton imageSource='/images/characters/07.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character08 = () => <CharacterButton imageSource='/images/characters/08.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character09 = () => <CharacterButton imageSource='/images/characters/09.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character10 = () => <CharacterButton imageSource='/images/characters/10.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character11 = () => <CharacterButton imageSource='/images/characters/11.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character12 = () => <CharacterButton imageSource='/images/characters/12.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character13 = () => <CharacterButton imageSource='/images/characters/13.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character14 = () => <CharacterButton imageSource='/images/characters/14.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character15 = () => <CharacterButton imageSource='/images/characters/15.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character16 = () => <CharacterButton imageSource='/images/characters/16.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character17 = () => <CharacterButton imageSource='/images/characters/17.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character18 = () => <CharacterButton imageSource='/images/characters/18.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character19 = () => <CharacterButton imageSource='/images/characters/19.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character20 = () => <CharacterButton imageSource='/images/characters/20.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character21 = () => <CharacterButton imageSource='/images/characters/21.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character22 = () => <CharacterButton imageSource='/images/characters/22.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character23 = () => <CharacterButton imageSource='/images/characters/23.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character24 = () => <CharacterButton imageSource='/images/characters/24.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character25 = () => <CharacterButton imageSource='/images/characters/25.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character26 = () => <CharacterButton imageSource='/images/characters/26.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character27 = () => <CharacterButton imageSource='/images/characters/27.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character28 = () => <CharacterButton imageSource='/images/characters/28.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character29 = () => <CharacterButton imageSource='/images/characters/29.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character30 = () => <CharacterButton imageSource='/images/characters/30.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character31 = () => <CharacterButton imageSource='/images/characters/31.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character32 = () => <CharacterButton imageSource='/images/characters/32.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character33 = () => <CharacterButton imageSource='/images/characters/33.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character34 = () => <CharacterButton imageSource='/images/characters/34.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character35 = () => <CharacterButton imageSource='/images/characters/35.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character36 = () => <CharacterButton imageSource='/images/characters/36.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character37 = () => <CharacterButton imageSource='/images/characters/37.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character38 = () => <CharacterButton imageSource='/images/characters/38.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character39 = () => <CharacterButton imageSource='/images/characters/39.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character40 = () => <CharacterButton imageSource='/images/characters/40.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character41 = () => <CharacterButton imageSource='/images/characters/41.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character42 = () => <CharacterButton imageSource='/images/characters/42.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character43 = () => <CharacterButton imageSource='/images/characters/43.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character44 = () => <CharacterButton imageSource='/images/characters/44.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character45 = () => <CharacterButton imageSource='/images/characters/45.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character46 = () => <CharacterButton imageSource='/images/characters/46.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character47 = () => <CharacterButton imageSource='/images/characters/47.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character48 = () => <CharacterButton imageSource='/images/characters/48.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character49 = () => <CharacterButton imageSource='/images/characters/49.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character50 = () => <CharacterButton imageSource='/images/characters/50.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character51 = () => <CharacterButton imageSource='/images/characters/51.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character52 = () => <CharacterButton imageSource='/images/characters/52.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character53 = () => <CharacterButton imageSource='/images/characters/53.png' size={500} onClick={() => window.alert('clicked!')}/>
export const character54 = () => <CharacterButton imageSource='/images/characters/54.png' size={500} onClick={() => window.alert('clicked!')}/>